%% Display setting and output setup
set(0,'ShowHiddenHandles','on'); delete(get(0,'Children')); % close windows
scr = get(groot,'ScreenSize');                              % screen resolution
phi = (1 + sqrt(5))/2;
scr_ratio = phi/3;
offset = [ scr(3)/4 scr(4)/4]; 
fig_pos = 
fig1 =  figure('Position',...                               % draw figure
        [offset(1) offset(2) scr(3)*scr_ratio scr(4)*scr_ratio]);
set(fig1,'numbertitle','off',...                            % Give figure useful title
        'name','Plot 1',...
        'Color','white');
fontName='CMU Serif';
fontSize = 28;
set(0,'defaultAxesFontName', fontName);                     % Make fonts pretty
set(0,'defaultTextFontName', fontName);
set(0,'DefaultAxesColor','none');                           % Transparent background
set(groot,'FixedWidthFontName', 'ElroNet Monospace')     

% Colors
cmap = colormap(lines);

line_thin = 2;
line_thick = 3;
marker_size = 8;
marker_spacing = 1;
len = 10;

% Draw plots
ax1 = axes();

p1 = plot(x,y(1,:)),...
    'Color', cmap(1,:),...
    'MarkerFaceColor',cmap(1,:),...
    'DisplayName','Data 1',...
	'LineStyle','-',...
	'LineWidth',line_thin,...
    'MarkerIndices',1:marker_spacing:len,...
    'Marker','o',...
    'MarkerSize',marker_size);
hold on

p2 = plot(x,y(2,:)),...
    'Color', cmap(2,:),...
    'MarkerFaceColor',cmap(2,:),...
    'DisplayName','Data2',...
	'LineStyle','-',...
	'LineWidth',line_thin,...
    'MarkerIndices',1:marker_spacing:len,...
    'Marker','o',...
    'MarkerSize',marker_size);
hold on

% Axes and labels
set(ax1,'FontSize',fontSize,...
    'Color','none',...
    'Box','off',...
    'XAxisLocation','origin',...
    'YMinorTick','on',...
    'XMinorTick','on',...
    'TickDir','both',...
    'Layer','top',...
    'LineWidth',line_thin,...
    'TickLabelInterpreter','latex');
set(ax1,...
    'Xlim',[floor(min(min(x))) ceil(max(max(x)))],...
    'Ylim',[floor(min(min(y))) ceil(max(max(y)))]);
hold on
xlabel('Resistance [k\Omega] \rightarrow',...
    'FontName',fontName,...
    'FontSize',fontSize);
ylabel('Voltage [V] \rightarrow',...
    'FontName',fontName,...
    'FontSize',fontSize);

% Title and Annotations
% t1 = title(ax1,'Voltage vs Resistance of a Strain Gauge');

% Legend
legend1 = legend;
set(legend1,...
     'Position',[0.519124425437305 0.740095701527999 0.193532818532818 0.132394109235202],...
     'Box','off');
hold on

% Adjust figure
ax1.Position = FillAxesPos(ax1,0.99);
% ax2.Position = ax1.Position;
% set(gca,'Layer','bottom')
hold off

clear ax1 ax2 cmap fontName fontSize legend1 len line_thin line_thick marker_size
clear marker_spacing offset p_hi p_lo p_nominal phi r1 r2 r3 scr scr_ratio